### ISSUE TITLE
[Question] does it support HiFi (1411 kb/s, 16/44.1khz)?

### ISSUE THREAD

**Issue by user5145** [fminetto/unofficial-deezer-player#3]

**Comment by fminetto** [comment]
Yes! This project is only a layer between Chromium Engine (Electron.js) and Deezer. So, any feature in the web version still working here!

**Comment by user5145** [comment]
but the web player doesnt support hifi. In windows it's only supported by Deezer Desktop app.

Chrome browser
![image](https://user-images.githubusercontent.com/16629139/63799811-2429fc80-c90d-11e9-80fa-075a124aec1a.png)


Deezer Music
![image](https://user-images.githubusercontent.com/16629139/63799855-386df980-c90d-11e9-8773-2e47f7482447.png)

**Comment by fminetto** [comment]
Ok, thanks for information! :+1:  :smile:

**Comment by user5145** [comment]
it may be worth to mention that aur has an unofficial player that supports hifi (FLAC) and to do so they decompress the official windows app and package it for linux.
https://aur.archlinux.org/packages/deezer/?PP=100#comment-683533
