### ISSUE TITLE
The browser version is no longer supported with our products (Deezer message)

### ISSUE THREAD

**Issue by sargentogato** [fminetto/unofficial-deezer-player#5]
The app is asking for an update of the browser. 

Thanks a million for your wonderfull work, the app is amazing.

**Comment by Natouriano** [comment]
Same here. After successful login, I get the following error: 
"Sorry, we don't support this version of your browser anymore. Update your browser or download our desktop app to keep enjoying your music."

**Comment by michaelsoko** [comment]
I'm experiencing the same issue on my end.

**Comment by asqwerty666** [comment]
I got the “edge” branch and compile it. The issue is solved by forcing the browser agent. dirty hack 👍 
see https://github.com/fminetto/unofficial-deezer-player/pull/8#issue-430335807

**Comment by veljkho** [comment]
So, will there be an update? Thanks @asqwerty666

**Comment by fminetto** [comment]
Update available on edge in snapstore, thank you :)
